In [1]:
import numpy as np

Creating array from List:

In [22]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d)
print(arr_1d.ndim)
print(arr_1d.shape)

1D array:  [1 2 3 4 5]
1
(5,)


In [24]:
arr_2d = np.array([[1,2,3],[4,5,6]])  #2d 2 rows & 3 cloumns
print(arr_2d)
print("Two dimenstional: ",arr_2d.ndim)
print("Shape: ",arr_2d.shape)

[[1 2 3]
 [4 5 6]]
Two dimenstional:  2
Shape:  (2, 3)


List vs Numpy array

In [5]:
# python list
py_list = [1,2,3]
print("Python list multiplication ",py_list * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]


In [9]:
#Numpy array
np_array = np.array([1,2,3]) # element wise multiplication
print("Python array multiplication ",np_array * 2)

Python array multiplication  [2 4 6]


In [16]:
import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.21937990188598633

 Numpy operation time:  0.012783527374267578


creating array from scratch: Methods

In [21]:
zeros = np.zeros([3,4])  # ---> rows & columns Shape
print("zeros array:\n", zeros)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
ones = np.ones([2,3]) # ---> rows & columns Shape
print("ones array:\n",ones)

ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
full = np.full((2,3), 7)
print("full array:\n",full)

full array:
 [[7 7 7]
 [7 7 7]]


In [33]:
random = np.random.random((2,3))
print("random array:\n",random)

random array:
 [[0.5916337  0.194746   0.92123161]
 [0.9892503  0.9801716  0.40598091]]


In [39]:
sequence = np.arange(0,11)
print("arange array:\n",sequence)

arange array:
 [ 0  1  2  3  4  5  6  7  8  9 10]


Vector , Matrix and Tensor :

In [41]:
Vector = np.array([1,2,3])
print("Vector :",Vector)

Vector : [1 2 3]


In [43]:
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix :\n",matrix)

Matrix :
 [[1 2 3]
 [4 5 6]]


In [47]:
tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]])
print("tensor :\n",tensor)
print("Shape :",tensor.shape)
print("Dimension :",tensor.ndim)

tensor :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape : (2, 2, 3)
Dimension : 3


Array properties:

In [52]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape :",arr.shape)
print("Dimension :",arr.ndim)
print("Size :",arr.size) # number of elements
print("Type :",arr.dtype)


Shape : (2, 3)
Dimension : 2
Size : 6
Type : int64


Array Reshaping:

In [82]:
arr = np.arange(12)
print("Original array:",arr)

reshaped = arr.reshape((3,4)) # 12 elements hai to 12 ka multiple hona chahiye
print("Reshaped array:\n",reshaped)

flattened = reshaped.flatten() 
print("flattened array:\n",flattened)

raveled = reshaped.ravel() 
print("raveled array:\n",raveled)

# Transpose
transpose = reshaped.T # ulta 2 x 3 = 3 x 2
print("transpose array:\n",transpose)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Numpy Array Operations: Indexing and Slicing

In [99]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:",arr[2:7])
print("With Step:",arr[1:8:2])
print("Negative indexing:",arr[-3])

Basic Slicing: [3 4 5 6 7]
With Step: [2 4 6 8]
Negative indexing: 8


In [132]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element:",arr_2d[1,2]) #rows & columns
print("Entire row:",arr_2d[1]) #rows & columns
print("Entire column:",arr_2d[:,2]) #rows & columns


Specific element: 6
Entire row: [4 5 6]
Entire column: [3 6 9]


Sorting:

In [136]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted Array", np.sort(unsorted))

Sorted Array [1 1 2 3 4 5 6 9]


In [141]:
arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("Sorted 2d Array by column\n", np.sort(arr_2d_unsorted, axis=0))

Sorted 2d Array by column
 [[1 1]
 [2 2]
 [3 3]]


Filter:

In [145]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even_numbers", even_number)

Even_numbers [ 2  4  6  8 10]


Filter with Mask:

In [149]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


Fancy Indexing vs np.where()

Adding and Removing Data:

In [152]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)


[1 2 3 4 5 6]


array compatiblity:

In [156]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatibility shapes", a.shape == b.shape )



Compatibility shapes False


In [160]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("With new column\n", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column
 [[1 2 7]
 [3 4 8]]


In [176]:
# Deleting data
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,[2])
print(deleted)


[1 2 4 5]


WS CUBE: CHANNEL

In [78]:
import numpy as np

In [84]:
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [85]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


Python List vs Numpy Arrays:

In [94]:
%timeit [j**4 for j in range(1,9)]

1.69 μs ± 80.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [95]:
import numpy as np
%timeit np.arange(1,9)**4

5.37 μs ± 29.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Numpy Array Creation;

In [105]:
import numpy as np

x = [1,2,3,4]

y = np.array([1,2,3,4,5])
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [104]:
l = []
for i in range(1,5):
    int_1 = int(input("Enter:"))
    l.append(int_1)

print(np.array(l))    

Enter: 1
Enter: 2
Enter: 3
Enter: 4


[1 2 3 4]


In [106]:
arr2 = np.array([[1,2,3,4],
                 [1,2,3,4]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [115]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
3


Special Types of Arrays (filed with specific value):

Zeros:

In [150]:
ar_zero = np.zeros((4))
ar_zero1 = np.zeros((3,4))
ar_zero2 = np.zeros((2,3,4))

print(ar_zero)
print()
print(ar_zero1)
print()
print(ar_zero2)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


Ones:

In [152]:
ar_one = np.ones((4))
ar_one1 = np.ones((3,4))
ar_one2 = np.ones((2,3,4))

print(ar_one)
print()
print(ar_one1)
print()
print(ar_one2)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Empty;

In [153]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


Range:

In [157]:
ar_rn = np.arange(1,6)
print(ar_rn)

[1 2 3 4 5]


Diagnol:

In [163]:
ar_dn = np.eye(4)
print(ar_dn)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


linspace:

In [172]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


Creating Random Valued Arrays: Create Numpy Arrays with Random Numbers:

Random:

In [180]:
#Rand:
var = np.random.rand(4)
print(var)

[0.5778977  0.60305742 0.857045   0.7481683 ]


In [182]:
var1 = np.random.rand(2,3)
print(var1)

[[0.32637518 0.87033731 0.10781048]
 [0.41912228 0.40036639 0.78953783]]


In [185]:
#Randn:
var2 = np.random.randn(2,3)
print(var2)

[[-1.85270734  0.19129818  1.18943854]
 [-0.58536195  0.685546   -0.16779392]]


In [193]:
#ranf:
var3 = np.random.ranf(4)
print(var3)

[0.21402977 0.64277995 0.65410353 0.25775714]


In [233]:
#Randint:
var4 = np.random.randint(5,20,5)
print(var4)

[ 5  6 10 12 13]


Numpy Data Types: Data Types in Numpy Arrays

In [241]:
var = np.array([1,2,3,4])
print(var.dtype)

int64


In [242]:
var = np.array([1.0,1.2,1.3])
print(var.dtype)

float64


In [243]:
var = np.array(["A","s","D","F"])
print(var.dtype)

<U1


In [246]:
var = np.array(["A","s","D","F",1,2,3,4,4])
print(var.dtype)

<U21


In [249]:
x = np.array([1,2,3,4],dtype = np.int8)
print(x.dtype)
print(x)

int8
[1 2 3 4]


In [257]:
x1 = np.array([1,2,3,4],dtype ="f")
print(x1.dtype)
print(x1)

float32
[1. 2. 3. 4.]


In [260]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

print(x2.dtype)
print(new.dtype)
print(x2)
print(new)

int64
float32
[1 2 3 4]
[1. 2. 3. 4.]


In [262]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)
new1 = np.int8(x2)
print(x2.dtype)
print(new.dtype)
print(new1.dtype)
print(x2)
print(new)
print(new1)

int64
float32
int8
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [268]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)
print(x3)
print(new_1)


[1 2 3 4]
[1. 2. 3. 4.]


In [287]:
var4 = np.array(['2','5','6'])

new5 = var4.astype(int)
print(var4)
print(new5)

['2' '5' '6']
[2 5 6]


Shape and Reshape in Numpy:Shape & Reshaping in Numpy Arrays  

In [291]:
var = np.array([[1,2,3],
                [1,2,3]])
print(var.shape)

(2, 3)


Reshape:

In [308]:
var3 = np.array([1,2,3,4,5,6,7,8,9])
print(var3)
print()

x = var3.reshape(3,3) 
print(x)

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [333]:
var4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var4)
print()

x1 = var4.reshape(2,3,2) 
print(x1)
print()

one = x1.reshape(-1)
print(one)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Indexing & Slicing in Numpy array:

In [39]:
# Indexing: 1d dimenstional
import numpy as np

var = np.array([9,8,7,6])
print(var[1])
print(var[-3])

8
8


In [41]:
#INDEXING 2d dimenstional
var1 = np.array([[9,8,7],
                 [4,5,6]])
print(var1)
print(var1.ndim) # dimanestion
print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2
7


In [43]:
#indexing: 3d dimaenstional
var2 = np.array([[[1,2],[6,7]]])
print(var2)
print(var2.ndim)
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3
7


In [57]:
# Slicing Numpy Array: 
var = np.array([1,2,3,4,5,6,7])  # 1d dimenstional
print(var)
print(var[1:5])
print(var[1:]) 
print(var[:5])  # start stop step
print(var[::2])
print(var[1:6:2])

[1 2 3 4 5 6 7]
[2 3 4 5]
[2 3 4 5 6 7]
[1 2 3 4 5]
[1 3 5 7]
[2 4 6]


In [81]:
#Slicing: 2d dimenstional
var1 = np.array([[9,8,7,6,9],
                [11,12,13,14,15],
                [21,22,23,24,25],
                [45,67,87,37,23]])
print(var1)
print(var1.ndim)
print(var1[1,1:5])

[[ 9  8  7  6  9]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [45 67 87 37 23]]
2
[12 13 14 15]


In [86]:
#Slicing: 3d dimenstional
var1 = np.array([[[9,8,7,6,9],
                [11,12,13,14,15]],
                [[21,22,23,24,25],
                [45,67,87,37,23]]])
print(var1)
print(var1.ndim)
print(var1[1,1,1:4])

[[[ 9  8  7  6  9]
  [11 12 13 14 15]]

 [[21 22 23 24 25]
  [45 67 87 37 23]]]
3
[67 87 37]


Numpy Array iteration:

In [94]:
import numpy as np
var = np.array([9,8,7,6,5,4]) # 1d dimenstional
print(var)
for i in var:
    print(i)

[9 8 7 6 5 4]
9
8
7
6
5
4


In [124]:
var1 = np.array([[1,2,3,4],
                 [5,6,7,8]])   # 2d dimenstional
print(var1)
for i in var1:
    for j in i:
        print(j)

[[1 2 3 4]
 [5 6 7 8]]
1
2
3
4
5
6
7
8


In [119]:
var2 = np.array([[[1,2,3,4],
                  [5,6,7,8]],
                [[9,10,11,12],
                [13,14,15,16]]]) #3d dimenstional

print(var2)
print( var2.ndim)
for i in var2:
    for j in i:
        for k in j:
            print(k)


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


nditer: function

In [8]:
var2 = np.array([[[1,2,3,4],
                  [5,6,7,8]],
                [[9,10,11,12],
                [13,14,15,16]]]) #3d dimenstional

print(var2)
print( var2.ndim)
for i in np.nditer(var2):
    print(i)


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [15]:
#iteration index value bhi de sakte hai kis k0o iterate karwana hai
import numpy as np
var2 = np.array([[[1,2,3,4],
                  [5,6,7,8]],
                [[9,10,11,12],
                [13,14,15,16]]]) #3d dimenstional

print(var2)
print(var2.ndim)
for i in np.nditer(var2[1,1]):
    print(i)



[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
13
14
15
16


In [125]:
#ndenumerate: function
var2 = np.array([[[1,2,3,4],
                  [5,6,7,8]],
                [[9,10,11,12],
                [13,14,15,16]]]) #3d dimenstional

print(var2)
print( var2.ndim)
for i,d in np.ndenumerate(var2):
    print(i,d)


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(1, 0, 0) 9
(1, 0, 1) 10
(1, 0, 2) 11
(1, 0, 3) 12
(1, 1, 0) 13
(1, 1, 1) 14
(1, 1, 2) 15
(1, 1, 3) 16


Numpy-Arithmetic Operations:

In [17]:
import numpy as np

In [21]:
var = np.array([1,2,3,4])

varadd = var + 3
print(varadd)

[4 5 6 7]


In [25]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2
print(varadd)

[2 4 6 8]


In [26]:
var = np.array([1,2,3,4])

varadd = var - 3
print(varadd)

[-2 -1  0  1]


In [46]:
var = np.array([1,2,3,4])

varadd = var * 3
print(varadd)

[ 3  6  9 12]


In [31]:
var = np.array([1,2,3,4])

varadd = var / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [32]:
var = np.array([1,2,3,4])

varadd = var % 3
print(varadd)

[1 2 0 1]


In [33]:
#array Functions arithmetic:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,var2)
print(varadd)

[2 4 6 8]


In [37]:
# Function
var = np.array([1,2,3,4])

varadd = np.add(var,3)
print(varadd)

[4 5 6 7]


2D Dimenstional Array:

In [45]:
var21 = np.array([[1,2,3,4],[5,6,7,8]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])
print(var21)
print()
print(var22)
print()
varadd2 = var21 * var22
print(varadd2)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 5 12 21 32]]


In [48]:
import numpy as np

In [9]:
var = np.array([4,6,1,8,5,3,2]) #1d dimenstional
print("min :",np.min(var),np.argmin(var))
print("max :",np.max(var),np.argmax(var))
print("sqrt :",np.sqrt(var))

min : 1 2
max : 8 3
sqrt : [2.         2.44948974 1.         2.82842712 2.23606798 1.73205081
 1.41421356]


In [66]:
var1 = np.array([[2,3,1], #2d dimenstional
                 [9,5,6]])
print("min :",np.min(var1,axis=1))#axis = 0 column axis = 1 row


min : [1 5]


In [77]:
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


The Difference Between Copy and View:

In [11]:
import numpy as np

In [20]:
var = np.array([1,2,3,4])

co = var.copy()

var[1] = 40

print('var :',var)
print('copy :',co)

var : [ 1 40  3  4]
copy : [1 2 3 4]


In [21]:
x = np.array([1,2,3,4])

vi = x.view()

x[1] = 40

print('x :',x)
print('view :',vi)

x : [ 1 40  3  4]
view : [ 1 40  3  4]


Join & Split Function:

Join Array:

In [26]:
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [48]:
vr = np.array([[1,2],
               [3,4]])
vr1 = np.array([[9,8],
                [7,6]])

ar_new = np.concatenate((vr,vr1),axis=0)
print(vr)
print()
print(vr1)
print()
print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


Stack:

In [64]:
vr_1 = np.array([1,2,3,4])
vr_2 = np.array([9,8,7,6])

a_new = np.stack((vr_1,vr_2),axis=1)
a_new1 = np.hstack((vr_1,vr_2)) # row
a_new2 = np.vstack((vr_1,vr_2)) # colums
a_new3 = np.dstack((vr_1,vr_2)) # height

print(a_new)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


Split Array:

Splitting breaks one array into multilpe.

In [77]:
import numpy as np
var = np.array([1,2,3,4,5,6])
print(var)

ar = np.array_split(var,3)
print()
print(ar)
print(ar[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [85]:
var1 = np.array([[1,2],
                 [3,4],
                 [5,6]])
print(var)

ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis=1)
print()
print(ar1)
print()
print(ar2)


[1 2 3 4 5 6]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]


Search,sort,Search Shorted,Filter Functions:

Search:

In [2]:
import numpy as np

In [14]:
var = np.array([4,2,3,4,2,5,2,5,6,7])

x = np.where( var == 2 )
print(x)

(array([1, 4, 6]),)


In [13]:
var = np.array([4,2,3,4,2,5,2,5,6,7])

x = np.where( (var%2) == 0 )
print(x)

(array([0, 1, 3, 4, 6, 8]),)


Search Sorted Array:

Sort array

In [15]:
var_1 = np.array([4,2,3,1,12,5,22,52,6,7])

print(np.sort(var_1))

[ 1  2  3  4  5  6  7 12 22 52]


In [17]:
var_1 = np.array([[4,2,3],[1,12,5],[22,52,6]])

print(np.sort(var_1))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


In [16]:
var_1 = np.array(['A','z','d','v'])

print(np.sort(var_1))

['A' 'd' 'v' 'z']


In [22]:
var_3 = np.array(['a','s','d','f'])

f = [True,False,False,True]

new_a = var_3[f]
print(new_a)


['a' 'f']


Shuffle , Unique , Resize , Flatten , Ravel Functons:

In [29]:
import numpy as np
var = np.array([1,2,3,4,5])

np.random.shuffle(var)
print(var)

[5 2 3 1 4]


In [35]:
#Unique:
var1 = np.array([1,2,3,4,2,5,2,6,2,7])

x = np.unique(var1,return_index=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9]))


Resize:

In [36]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


Flatten:

In [43]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(2,3))
print(y)
print()
print("flatten :",y.flatten())
print("Ravel :",np.ravel(y))

[[1 2 3]
 [4 5 6]]

flatten : [1 2 3 4 5 6]
Ravel : [1 2 3 4 5 6]


Insert and Delete Functions:

Insert:

In [54]:
var = np.array([1,2,3,4])

print(var)

# v = np.insert(var,(2,4),40)
v = np.append(var,40)
print(v)

[1 2 3 4]
[ 1  2  3  4 40]


In [57]:
var1 = np.array([[1,2,3],[4,5,6]])
print(var1)
print()
# v1 = np.insert(var1,2,6,axis=0)
v1 = np.append(var1,[[45,44,23]],axis=0)
print(v1)

[[1 2 3]
 [4 5 6]]

[[ 1  2  3]
 [ 4  5  6]
 [45 44 23]]


Delete:

In [58]:
var1 = np.array([1,2,3,4])

print(var1)

d = np.delete(var1,2)
print(d)

[1 2 3 4]
[1 2 4]


Transpose:

In [63]:
var = np.array([[1,2,3],[4,5,6]])

print(var)
print()

print(np.transpose(var))
print()
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


Broadcasting with Numpy Arrays:

In [1]:
import numpy as np

In [24]:
var1 = np.array([1,2,3])
print("Array1 :\n",var1)
print("Shape :\n",var1.shape)
print()
var2 = np.array([[1],[2],[3]])
print("Array2 :\n",var2)
print("Shape :\n",var2.shape)
print()
print("Broadcasting :\n",var1 + var2)

Array1 :
 [1 2 3]
Shape :
 (3,)

Array2 :
 [[1]
 [2]
 [3]]
Shape :
 (3, 1)

Broadcasting :
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [41]:
x = np.array([[1],[2]])
print(x)
print("Shape :",x.shape)
print()

y = np.array([[1,2,3],[4,5,6]])
print(y)
print("Shape :\n",y.shape)
print()
print("Broadcasting :\n",x+y)

[[1]
 [2]]
Shape : (2, 1)

[[1 2 3]
 [4 5 6]]
Shape :
 (2, 3)

Broadcasting :
 [[2 3 4]
 [6 7 8]]
